resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: gpdb_pr
    type: pull-request
    source:
      repository: greenplum-db/gpdb
      access_token: ((gpdb-git-access-token))
      base_branch: "5X_STABLE"
      ignore_paths:
        - gpdb-doc/*
        - README*

  - name: centos-gpdb-dev-6
    type: docker-image
    source:
      repository: pivotaldata/centos-gpdb-dev
      tag: '6-gcc6.2-llvm3.7'

  - name: gpaddon_src
    type: git
    source:
      branch: "5X_STABLE"
      private_key: {{gpaddon-git-key}}
      uri: {{gpaddon-git-remote}}


jobs:
  - name: compile-and-test-pull-request
    plan:
      - aggregate:
          - get: gpdb_pr
            version: every
            trigger: true
          - get: centos-gpdb-dev-6
          - get: gpaddon_src
      - put: gpdb_pr
        params:
          path: gpdb_pr
          status: pending
      - task: sync_tools
        file: gpdb_pr/concourse/tasks/sync_tools.yml
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
        params:
          IVYREPO_HOST: {{ivyrepo_host}}
          IVYREPO_REALM: {{ivyrepo_realm}}
          IVYREPO_USER: {{ivyrepo_user}}
          IVYREPO_PASSWD: {{ivyrepo_passwd}}
          TARGET_OS: centos
          TARGET_OS_VERSION: 6
          TASK_OS: centos
          TASK_OS_VERSION: 6
      - task: compile_gpdb_centos6
        file: gpdb_pr/concourse/tasks/compile_gpdb.yml
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
        on_failure: &pr_failure
          put: gpdb_pr
          params:
            path: gpdb_pr
            status: failure
        params:
          CONFIGURE_FLAGS: {{configure_flags}}
          TARGET_OS: centos
          TARGET_OS_VERSION: 6
          BLD_TARGETS: "clients loaders"
      - task: ic_gpdb
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        on_failure: *pr_failure
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=off' installcheck-world
          BLDWRAP_POSTGRES_CONF_ADDONS: "fsync=off"
          TEST_OS: centos
          CONFIGURE_FLAGS: {{configure_flags}}

      - put: report_pr_success
        resource: gpdb_pr
        params:
          path: gpdb_pr
          status: success
