PG_CONFIG = pg_config

MODULE_big = get_best_database
OBJS = get_best_database.o query.o

top_builddir = ../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk
